name: Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Atualiza a cada 12 horas

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação da cobrinha
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake-light.svg?palette=github-light

      - name: Fazer commit do resultado
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Atualizando animação da cobrinha"
          branch: output
